spring.application.name=JPA

# H2 désactivé
spring.h2.console.enabled=false

# Connexion à SQL Server Express
spring.datasource.url=jdbc:sqlserver://localhost\\SQLEXPRESS:1433;databaseName=users_db;encrypt=true;trustServerCertificate=true
spring.datasource.username=ton_utilisateur
spring.datasource.password=ton_mot_de_passe
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# Port du serveur Spring Boot
server.port=8083
